#!/usr/bin/python
import rospy
import itertools
#import ros_numpy
import message_filters
from std_msgs.msg import Int64, String
from sensor_msgs.msg import CompressedImage, Image, JointState
from geometry_msgs.msg import Twist, Pose
import numpy as np
import os
from scipy.misc import imshow
import cv2 
import time
import csv
import os
import sys

# Global Variables
#The first argument should be the task that we are doing
task = sys.argv[1]
if not os.path.exists('datas/' + task + '/'):
  os.mkdir('datas/' + task + '/')
save_folder=None
writer = None
text_file = None
is_recording = False
counter = 0

class ApproxTimeSync(message_filters.ApproximateTimeSynchronizer):
  def add(self, msg, my_queue, my_queue_index=None):
        self.allow_headerless = True
        if hasattr(msg, 'timestamp'):
            stamp = msg.timestamp
        elif not hasattr(msg, 'header') or not hasattr(msg.header, 'stamp'):
            if not self.allow_headerless:
                rospy.logwarn("Cannot use message filters with non-stamped messages. "
                              "Use the 'allow_headerless' constructor option to "
                              "auto-assign ROS time to headerless messages.")
                return
            stamp = rospy.Time.now()
	else:
            stamp = msg.header.stamp
	
	#TODO ADD HEADER TO ALLOW HEADERLESS
	# http://book2code.com/ros_kinetic/source/ros_comm/message_filters/src/message_filters/__init__.y
        #setattr(msg, 'header', a)
        #msg.header.stamp = stamp
	#super(message_filters.ApproximateTimeSynchronizer, self).add(msg, my_queue)
        self.lock.acquire()
        my_queue[stamp] = msg
        while len(my_queue) > self.queue_size:
            del my_queue[min(my_queue)]
        # self.queues = [topic_0 {stamp: msg}, topic_1 {stamp: msg}, ...]
        if my_queue_index is None:
            search_queues = self.queues
        else:
            search_queues = self.queues[:my_queue_index] + \
                self.queues[my_queue_index+1:]
        # sort and leave only reasonable stamps for synchronization
        stamps = []
        for queue in search_queues:
            topic_stamps = []
            for s in queue:
                stamp_delta = abs(s - stamp)
                if stamp_delta > self.slop:
                    continue  # far over the slop
                topic_stamps.append((s, stamp_delta))
            if not topic_stamps:
                self.lock.release()
                return
            topic_stamps = sorted(topic_stamps, key=lambda x: x[1])
            stamps.append(topic_stamps)
        for vv in itertools.product(*[zip(*s)[0] for s in stamps]):
            vv = list(vv)
            # insert the new message
            if my_queue_index is not None:
                vv.insert(my_queue_index, stamp)
            qt = list(zip(self.queues, vv))
            if ( ((max(vv) - min(vv)) < self.slop) and
                (len([1 for q,t in qt if t not in q]) == 0) ):
                msgs = [q[t] for q,t in qt]
                self.signalMessage(*msgs)
                for q,t in qt:
                    del q[t]
                break  # fast finish after the synchronization
        self.lock.release()

def callback(pose, vels, rgb, depth, gripper):
  curr_time = str(time.time())
  # We are toggling this global variable
  global is_recording
  global save_folder
  global writer
  global counter
  if not is_recording:
   return
  with open(save_folder + str(counter) + '_rgb.jpg', 'w') as f:
    f.write(rgb.data)
  with open(save_folder + str(counter) + '_depth.jpg', 'w') as f:
    f.write(depth.data)
  # end effector position
  posit = pose.position
  # end effector orientation
  orient = pose.orientation
  twist = vels
  # linear velocity
  lin = twist.linear
  # angular velocity
  ang = twist.angular
  arr = [counter, posit.x, posit.y, posit.z]
  arr += [orient.w, orient.x, orient.y, orient.z]
  arr += [lin.x, lin.y, lin.z]
  arr += [ang.x, ang.y, ang.z]
  arr += [gripper.data, float(curr_time)]
  if writer != None:
      writer.writerow(arr)
  else:
      print('WARNING: UNABLE TO WRITE DATA TO WRITER!') 
  counter += 1

def record(value):
  global save_folder
  global task
  global is_recording
  global text_file
  global writer
  global counter
  print("This is value")
  print(value.data)
  if value.data == "0":
    counter = 0
    if is_recording == False:
      return
    else:
      if text_file != None:
        text_file.close()
        text_file = None
        print('File closed')
      is_recording=False
      print('STOP')
  else:
    save_folder_tmp='datas/' + task + '/' + str(time.time()) + '/'
    os.mkdir(save_folder_tmp)
    save_folder = save_folder_tmp
    print('save folder changed: %s' % save_folder)
    text_file = open(save_folder + 'vectors.txt', 'w')
    writer = csv.writer(text_file)
    is_recording = True
    print('START')

#TODO CONSIDER COMPRESSED IMAGES 
#joint_state_sub = message_filters.Subscriber('/robot/joint_states', JointState)
right_arm_pose = message_filters.Subscriber('/tf/right_arm_pose', Pose)
right_arm_vel = message_filters.Subscriber('/tf/right_arm_vels', Twist)
rgb_state_sub = message_filters.Subscriber('/kinect2/sd/image_color_rect/compressed', CompressedImage)
depth_state_sub = message_filters.Subscriber('/kinect2/sd/image_depth_rect/compressed', CompressedImage)
gripper_state_sub = message_filters.Subscriber('/gripper_is_open', Int64)
#gripper_cache = message_filters.Cache(gripper_state_sub)
#mode_sub = message_filters.Subscriber('mode', Int32)
#penalty_sub = message_filters.Subscriber('penalty', Float32)

rospy.init_node('imitate_recorder', log_level=rospy.DEBUG)
#ts = message_filters.ApproximateTimeSynchronizer
ts = ApproxTimeSync([right_arm_pose, right_arm_vel, rgb_state_sub,  depth_state_sub, gripper_state_sub], 1, 0.1)
ts.registerCallback(callback)

# Toggle
toggle_button = message_filters.Subscriber('/unity_learning_record', String)
toggle_button.registerCallback(record)

print('Spinning')
rospy.spin()